#! /bin/bash
read -rsp 'Password: ' ES_PASS

echo "====Space setting===="
curl --cacert /etc/kibana/certs/elasticsearch-ca.pem -u elastic:$ES_PASS -X PUT "http://localhost:5601/api/spaces/space/default" -H 'Content-Type: application/json' -H "kbn-xsrf: reporting"  -d '
{
"id": "default",
"name": "Default",
"disabledFeatures": ["canvas","maps","ml","enterpriseSearch","logs","infrastructure","graph","apm","uptime","observabilityCases","siem","securitySolutionCases","dev_tools","savedObjectsTagging","osquery","actions","stackAlerts","fleetv2","fleet","monitoring"]
}
'

echo "====Import objects===="
curl --cacert /etc/kibana/certs/elasticsearch-ca.pem -u elastic:$ES_PASS -X POST "http://localhost:5601/api/saved_objects/_import?overwrite=true" -H "kbn-xsrf: true" --form file=@src/kibana/export.ndjson


echo "====Backup repo===="
curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:$ES_PASS -XPUT "https://localhost:9200/_snapshot/snapshot?pretty"  -H 'Content-Type: application/json' -d '{
    "type": "fs",
    "settings": {
        "location": "/var/lib/APC/backup/",
        "compress": true
    }
}'

echo "====Create role===="
curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:$ES_PASS -XPOST "https://localhost:9200/_security/role/data_stream?pretty" -H "Content-Type: application/json" -d'
{
  "cluster": ["all"],
  "indices": [
    {
      "names": ["*"],
      "privileges": ["all"]
    }
  ]
}
'

echo "====Create user===="
curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:$ES_PASS -XPOST "https://localhost:9200/_security/user/data_stream_user?pretty" -H "Content-Type: application/json" -d'
{
  "password" : "Data_stream_pw",
  "roles" : [ "data_stream" ]
}
'

echo "====Logrotate settings===="
curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:"$ES_PASS" -XPUT "https://localhost:9200/_ilm/policy/forti_ilm_policy_001" -H "kbn-xsrf: reporting" -H 'Content-Type: application/json' -d '
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "30d",
            "max_primary_shard_size": "50gb"
          },
          "set_priority": {
            "priority": 100
          }
        },
        "min_age": "0ms"
      }
    }
  }
}
'

curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:"$ES_PASS" -XPUT "https://localhost:9200/_ilm/policy/palo_ilm_policy_001" -H "kbn-xsrf: reporting" -H 'Content-Type: application/json' -d '
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "30d",
            "max_primary_shard_size": "50gb"
          },
          "set_priority": {
            "priority": 100
          }
        },
        "min_age": "0ms"
      }
    }
  }
}
'

curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:"$ES_PASS" -XPUT "https://localhost:9200/_ilm/policy/nozomi_ilm_policy_001" -H "kbn-xsrf: reporting" -H 'Content-Type: application/json' -d '
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "30d",
            "max_primary_shard_size": "50gb"
          },
          "set_priority": {
            "priority": 100
          }
        },
        "min_age": "0ms"
      }
    }
  }
}
'



echo "====Template setting Fortigate===="
curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:$ES_PASS -XPUT "https://localhost:9200/_template/forti_template_01?pretty" -H 'Content-Type: application/json' -d '
{
  "index_patterns" : ["forti_syslog_*"],
  "settings" : {
    "number_of_shards" : 1,
    "number_of_replicas" : 0,
    "refresh_interval" : "1s",
    "index.lifecycle.name": "forti_ilm_policy_001",      
    "index.lifecycle.rollover_alias": "forti_syslog" 
  },
  "mappings" : {
      "dynamic_templates": [{
        "defaultmapping_notanalyzed": {
          "match": "*",
          "match_mapping_type": "string",
          "mapping": {"type": "keyword", "index": "false"}
        }
      }],
     "properties": {
      "receive_time": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "eventtime": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "appact" : {"type":"keyword","index":"true"},
      "action" : {"type":"keyword","index":"true"},
      "attackid" : {"type":"integer","index":"true"},
      "count" : {"type":"integer","index":"true"},
      "craction" : {"type":"keyword","index":"true"},
      "crlevel" : {"type":"keyword","index":"true"},
      "crscore" : {"type":"integer","index":"true"},
      "dstintf" : {"type":"keyword","index":"true"},
      "dstip" : {"type":"ip","index":"true"},
      "dstport" : {"type":"integer","index":"true"},
      "eventtype" : {"type":"keyword","index":"true"},
      "group" : {"type":"keyword","index":"true"},
      "level" : {"type":"keyword","index":"true"},
      "attack" : {"type":"keyword","index":"true"},
      "logid" : {"type":"keyword","index":"true"},
      "msg" : {"type":"keyword","index":"true"},
      "policyid" : {"type":"integer","index":"true"},
      "policytype" : {"type":"keyword","index":"true"},
      "proto" : {"type":"integer","index":"true"},
      "ref" : {"type":"keyword","index":"true"},
      "service" : {"type":"keyword","index":"true"},
      "sessionid" : {"type":"long","index":"true"},
      "severity" : {"type":"keyword","index":"true"},
      "srcintf" : {"type":"keyword","index":"true"},
      "srcip" : {"type":"ip","index":"true"},
      "srcport" : {"type":"integer","index":"true"},
      "subtype" : {"type":"keyword","index":"true"},
      "type" : {"type":"keyword","index":"true"},
      "user" : {"type":"keyword","index":"true"},
      "vd" : {"type":"keyword","index":"true"},
      "icmpcode" : {"type":"keyword","index":"true"},
      "icmpid" : {"type":"keyword","index":"true"},
      "icmptype" : {"type":"keyword","index":"true"},
      "app" : {"type":"keyword","index":"true"},
      "appcat" : {"type":"keyword","index":"true"},
      "applist" : {"type":"keyword","index":"true"},
      "direction" : {"type":"keyword","index":"true"},
      "profiletype" : {"type":"keyword","index":"true"},
      "appid" : {"type":"integer","index":"true"},
      "apprisk" : {"type":"keyword","index":"true"},
      "cloudaction" : {"type":"keyword","index":"true"},
      "clouduser" : {"type":"keyword","index":"true"},
      "filename" : {"type":"keyword","index":"true"},
      "filesize" : {"type":"long","index":"true"},
      "hostname" : {"type":"keyword","index":"true"},
      "url" : {"type":"keyword","index":"true"},
      "agent" : {"type":"keyword","index":"true"},
      "analyticscksum" : {"type":"keyword","index":"true"},
      "analyticssubmit" : {"type":"keyword","index":"true"},
      "dtype" : {"type":"keyword","index":"true"},
      "from" : {"type":"keyword","index":"true"},
      "profile" : {"type":"keyword","index":"true"},
      "quarskip" : {"type":"keyword","index":"true"},
      "recipient" : {"type":"keyword","index":"true"},
      "sender" : {"type":"keyword","index":"true"},
      "to" : {"type":"keyword","index":"true"},
      "virus" : {"type":"keyword","index":"true"},
      "filefilter" : {"type":"keyword","index":"true"},
      "filetype" : {"type":"keyword","index":"true"},
      "command" : {"type":"keyword","index":"true"},
      "switchproto" : {"type":"keyword","index":"true"},
      "virusid" : {"type":"integer","index":"true"},
      "dlpextra" : {"type":"keyword","index":"true"},
      "epoch" : {"type":"integer","index":"true"},
      "eventid" : {"type":"integer","index":"true"},
      "filtercat" : {"type":"keyword","index":"true"},
      "filteridx" : {"type":"integer","index":"true"},
      "filtername" : {"type":"keyword","index":"true"},
      "filtertype" : {"type":"keyword","index":"true"},
      "rcvdbyte" : {"type":"long","index":"true"},
      "sentbyte" : {"type":"long","index":"true"},
      "subject" : {"type":"keyword","index":"true"},
      "docsource" : {"type":"keyword","index":"true"},
      "sensitivity" : {"type":"keyword","index":"true"},
      "attachment" : {"type":"keyword","index":"true"},
      "banword" : {"type":"keyword","index":"true"},
      "cc" : {"type":"keyword","index":"true"},
      "fortiguardresp" : {"type":"keyword","index":"true"},
      "size" : {"type":"keyword","index":"true"},
      "devid" : {"type":"keyword","index":"true"},
      "devname" : {"type":"keyword","index":"true"},
      "logdesc" : {"type":"keyword","index":"true"},
      "status" : {"type":"keyword","index":"true"},
      "ui" : {"type":"keyword","index":"true"},
      "nat" : {"type":"ip","index":"true"},
      "datarange" : {"type":"keyword","index":"true"},
      "file" : {"type":"keyword","index":"true"},
      "processtime" : {"type":"integer","index":"true"},
      "reporttype" : {"type":"keyword","index":"true"},
      "intf" : {"type":"keyword","index":"true"},
      "error" : {"type":"keyword","index":"true"},
      "port" : {"type":"integer","index":"true"},
      "server" : {"type":"keyword","index":"true"},
      "daemon" : {"type":"keyword","index":"true"},
      "pid" : {"type":"integer","index":"true"},
      "limit" : {"type":"integer","index":"true"},
      "name" : {"type":"keyword","index":"true"},
      "process" : {"type":"keyword","index":"true"},
      "reason" : {"type":"keyword","index":"true"},
      "conserve" : {"type":"keyword","index":"true"},
      "free" : {"type":"keyword","index":"true"},
      "red" : {"type":"keyword","index":"true"},
      "green" : {"type":"keyword","index":"true"},
      "poolname" : {"type":"keyword","index":"true"},
      "saddr" : {"type":"keyword","index":"true"},
      "portbegin" : {"type":"integer","index":"true"},
      "portend" : {"type":"integer","index":"true"},
      "duration" : {"type":"integer","index":"true"},
      "fams_pause" : {"type":"integer","index":"true"},
      "used" : {"type":"integer","index":"true"},
      "unit" : {"type":"integer","index":"true"},
      "cert" : {"type":"keyword","index":"true"},
      "mode" : {"type":"keyword","index":"true"},
      "total" : {"type":"integer","index":"true"},
      "entermargin" : {"type":"integer","index":"true"},
      "exitmargin" : {"type":"integer","index":"true"},
      "sysconserve" : {"type":"keyword","index":"true"},
      "interface" : {"type":"keyword","index":"true"},
      "probeproto" : {"type":"keyword","index":"true"},
      "dhcp_msg" : {"type":"keyword","index":"true"},
      "ip" : {"type":"ip","index":"true"},
      "lease" : {"type":"integer","index":"true"},
      "mac" : {"type":"keyword","index":"true"},
      "ddnsserver" : {"type":"ip","index":"true"},
      "fqdn" : {"type":"keyword","index":"true"},
      "duid" : {"type":"keyword","index":"true"},
      "iaid" : {"type":"keyword","index":"true"},
      "assigned" : {"type":"ip","index":"true"},
      "local" : {"type":"ip","index":"true"},
      "remote" : {"type":"ip","index":"true"},
      "gateway" : {"type":"ip","index":"true"},
      "mtu" : {"type":"integer","index":"true"},
      "community" : {"type":"keyword","index":"true"},
      "version" : {"type":"keyword","index":"true"},
      "method" : {"type":"keyword","index":"true"},
      "sn" : {"type":"keyword","index":"true"},
      "log" : {"type":"keyword","index":"true"},
      "hash" : {"type":"keyword","index":"true"},
      "module" : {"type":"keyword","index":"true"},
      "submodule" : {"type":"keyword","index":"true"},
      "field" : {"type":"keyword","index":"true"},
      "new_status" : {"type":"keyword","index":"true"},
      "old_status" : {"type":"keyword","index":"true"},
      "passwd" : {"type":"keyword","index":"true"},
      "crl" : {"type":"keyword","index":"true"},
      "serialno" : {"type":"keyword","index":"true"},
      "alarmid" : {"type":"integer","index":"true"},
      "groupid" : {"type":"integer","index":"true"},
      "acktime" : {"type":"keyword","index":"true"},
      "new_value" : {"type":"keyword","index":"true"},
      "old_value" : {"type":"keyword","index":"true"},
      "cfgattr" : {"type":"keyword","index":"true"},
      "cfgpath" : {"type":"keyword","index":"true"},
      "cpu" : {"type":"integer","index":"true"},
      "mem" : {"type":"integer","index":"true"},
      "assignip" : {"type":"ip","index":"true"},
      "cookies" : {"type":"keyword","index":"true"},
      "locip" : {"type":"ip","index":"true"},
      "locport" : {"type":"integer","index":"true"},
      "outintf" : {"type":"keyword","index":"true"},
      "remip" : {"type":"ip","index":"true"},
      "remport" : {"type":"integer","index":"true"},
      "result" : {"type":"keyword","index":"true"},
      "vpntunnel" : {"type":"keyword","index":"true"},
      "xauthgroup" : {"type":"keyword","index":"true"},
      "xauthuser" : {"type":"keyword","index":"true"},
      "espauth" : {"type":"keyword","index":"true"},
      "esptransform" : {"type":"keyword","index":"true"},
      "role" : {"type":"keyword","index":"true"},
      "peer_notif" : {"type":"keyword","index":"true"},
      "dir" : {"type":"keyword","index":"true"},
      "init" : {"type":"keyword","index":"true"},
      "stage" : {"type":"integer","index":"true"},
      "error_num" : {"type":"keyword","index":"true"},
      "seq" : {"type":"keyword","index":"true"},
      "spi" : {"type":"keyword","index":"true"},
      "in_spi" : {"type":"keyword","index":"true"},
      "out_spi" : {"type":"keyword","index":"true"},
      "nextstat" : {"type":"integer","index":"true"},
      "tunnelid" : {"type":"integer","index":"true"},
      "tunnelip" : {"type":"ip","index":"true"},
      "tunneltype" : {"type":"keyword","index":"true"},
      "phase2_name" : {"type":"keyword","index":"true"},
      "exch" : {"type":"keyword","index":"true"},
      "ha_group" : {"type":"integer","index":"true"},
      "vcluster" : {"type":"integer","index":"true"},
      "from_vcluster" : {"type":"integer","index":"true"},
      "to_vcluster" : {"type":"integer","index":"true"},
      "vdname" : {"type":"keyword","index":"true"},
      "devintfname" : {"type":"keyword","index":"true"},
      "ha_role" : {"type":"keyword","index":"true"},
      "hbdn_reason" : {"type":"keyword","index":"true"},
      "sync_status" : {"type":"keyword","index":"true"},
      "sync_type" : {"type":"keyword","index":"true"},
      "activity" : {"type":"keyword","index":"true"},
      "ha-prio" : {"type":"integer","index":"true"},
      "authproto" : {"type":"keyword","index":"true"},
      "msgproto" : {"type":"keyword","index":"true"},
      "nf_type" : {"type":"keyword","index":"true"},
      "profilegroup" : {"type":"keyword","index":"true"},
      "sess_duration" : {"type":"integer","index":"true"},
      "profile_vd" : {"type":"keyword","index":"true"},
      "acct_stat" : {"type":"keyword","index":"true"},
      "carrier_ep" : {"type":"keyword","index":"true"},
      "rsso_key" : {"type":"keyword","index":"true"},
      "desc" : {"type":"keyword","index":"true"},
      "bandwidth" : {"type":"keyword","index":"true"},
      "disk" : {"type":"integer","index":"true"},
      "disklograte" : {"type":"long","index":"true"},
      "fazlograte" : {"type":"long","index":"true"},
      "setuprate" : {"type":"long","index":"true"},
      "totalsession" : {"type":"long","index":"true"},
      "addr_type" : {"type":"keyword","index":"true"},
      "fwserver_name" : {"type":"keyword","index":"true"},
      "cert-type" : {"type":"keyword","index":"true"},
      "adgroup" : {"type":"keyword","index":"true"},
      "initiator" : {"type":"keyword","index":"true"},
      "expiry" : {"type":"keyword","index":"true"},
      "oldwprof" : {"type":"keyword","index":"true"},
      "scope" : {"type":"keyword","index":"true"},
      "stamac" : {"type":"keyword","index":"true"},
      "blocked" : {"type":"integer","index":"true"},
      "checksum" : {"type":"integer","index":"true"},
      "infected" : {"type":"integer","index":"true"},
      "intercepted" : {"type":"integer","index":"true"},
      "scanned" : {"type":"integer","index":"true"},
      "suspicious" : {"type":"integer","index":"true"},
      "age" : {"type":"integer","index":"true"},
      "apscan" : {"type":"keyword","index":"true"},
      "apstatus" : {"type":"integer","index":"true"},
      "aptype" : {"type":"integer","index":"true"},
      "bssid" : {"type":"keyword","index":"true"},
      "channel" : {"type":"integer","index":"true"},
      "detectionmethod" : {"type":"keyword","index":"true"},
      "encryption" : {"type":"keyword","index":"true"},
      "live" : {"type":"integer","index":"true"},
      "manuf" : {"type":"keyword","index":"true"},
      "noise" : {"type":"integer","index":"true"},
      "onwire" : {"type":"keyword","index":"true"},
      "radioband" : {"type":"keyword","index":"true"},
      "radioidclosest" : {"type":"integer","index":"true"},
      "radioiddetected" : {"type":"integer","index":"true"},
      "rate" : {"type":"integer","index":"true"},
      "security" : {"type":"keyword","index":"true"},
      "signal" : {"type":"integer","index":"true"},
      "snclosest" : {"type":"keyword","index":"true"},
      "sndetected" : {"type":"keyword","index":"true"},
      "ssid" : {"type":"keyword","index":"true"},
      "stacount" : {"type":"integer","index":"true"},
      "ap" : {"type":"keyword","index":"true"},
      "cfgtxpower" : {"type":"integer","index":"true"},
      "configcountry" : {"type":"keyword","index":"true"},
      "opercountry" : {"type":"keyword","index":"true"},
      "opertxpower" : {"type":"integer","index":"true"},
      "radioid" : {"type":"integer","index":"true"},
      "ds" : {"type":"keyword","index":"true"},
      "encrypt" : {"type":"integer","index":"true"},
      "frametype" : {"type":"keyword","index":"true"},
      "rssi" : {"type":"integer","index":"true"},
      "tamac" : {"type":"keyword","index":"true"},
      "threattype" : {"type":"keyword","index":"true"},
      "invalidmac" : {"type":"keyword","index":"true"},
      "weakwepiv" : {"type":"keyword","index":"true"},
      "eapolcnt" : {"type":"integer","index":"true"},
      "eapoltype" : {"type":"keyword","index":"true"},
      "mgmtcnt" : {"type":"integer","index":"true"},
      "meshmode" : {"type":"keyword","index":"true"},
      "snmeshparent" : {"type":"keyword","index":"true"},
      "vap" : {"type":"keyword","index":"true"},
      "addr" : {"type":"keyword","index":"true"},
      "banned_rule" : {"type":"keyword","index":"true"},
      "banned_src" : {"type":"keyword","index":"true"},
      "dst_int" : {"type":"keyword","index":"true"},
      "sensor" : {"type":"keyword","index":"true"},
      "src_int" : {"type":"keyword","index":"true"},
      "chassisid" : {"type":"integer","index":"true"},
      "informationsource" : {"type":"keyword","index":"true"},
      "slot" : {"type":"integer","index":"true"},
      "newchassisid" : {"type":"integer","index":"true"},
      "newslot" : {"type":"integer","index":"true"},
      "oldchassisid" : {"type":"integer","index":"true"},
      "oldslot" : {"type":"integer","index":"true"},
      "newchannel" : {"type":"integer","index":"true"},
      "oldchannel" : {"type":"integer","index":"true"},
      "cfgtid" : {"type":"integer","index":"true"},
      "cfgobj" : {"type":"keyword","index":"true"},
      "handshake" : {"type":"keyword","index":"true"},
      "identidx" : {"type":"integer","index":"true"},
      "serial" : {"type":"integer","index":"true"},
      "vip" : {"type":"keyword","index":"true"},
      "expectedhandshake" : {"type":"keyword","index":"true"},
      "receivedhandshake" : {"type":"keyword","index":"true"},
      "len" : {"type":"integer","index":"true"},
      "minminor" : {"type":"integer","index":"true"},
      "recvminor" : {"type":"integer","index":"true"},
      "max" : {"type":"integer","index":"true"},
      "maxminor" : {"type":"integer","index":"true"},
      "created" : {"type":"keyword","index":"true"},
      "session_id" : {"type":"long","index":"true"},
      "major" : {"type":"integer","index":"true"},
      "minor" : {"type":"integer","index":"true"},
      "ssl2" : {"type":"integer","index":"true"},
      "cipher" : {"type":"integer","index":"true"},
      "min" : {"type":"integer","index":"true"},
      "received" : {"type":"integer","index":"true"},
      "expectedsignature" : {"type":"integer","index":"true"},
      "receivedsignature" : {"type":"integer","index":"true"},
      "connection_type" : {"type":"keyword","index":"true"},
      "forticlient_id" : {"type":"keyword","index":"true"},
      "license_limit" : {"type":"keyword","index":"true"},
      "used_for_type" : {"type":"integer","index":"true"},
      "cveid" : {"type":"keyword","index":"true"},
      "devtype" : {"type":"keyword","index":"true"},
      "fctuid" : {"type":"keyword","index":"true"},
      "scantime" : {"type":"long","index":"true"},
      "srcname" : {"type":"keyword","index":"true"},
      "vendorurl" : {"type":"keyword","index":"true"},
      "vulncat" : {"type":"keyword","index":"true"},
      "vulnid" : {"type":"integer","index":"true"},
      "vulnname" : {"type":"keyword","index":"true"},
      "monitor-name" : {"type":"keyword","index":"true"},
      "monitor-type" : {"type":"keyword","index":"true"},
      "alert" : {"type":"keyword","index":"true"},
      "authgrp" : {"type":"keyword","index":"true"},
      "host" : {"type":"keyword","index":"true"},
      "peer" : {"type":"keyword","index":"true"},
      "app-type" : {"type":"keyword","index":"true"},
      "apn" : {"type":"keyword","index":"true"},
      "c-gsn" : {"type":"ip","index":"true"},
      "end-usr-address" : {"type":"ip","index":"true"},
      "headerteid" : {"type":"integer","index":"true"},
      "imei-sv" : {"type":"keyword","index":"true"},
      "imsi" : {"type":"keyword","index":"true"},
      "linked-nsapi" : {"type":"integer","index":"true"},
      "msg-type" : {"type":"integer","index":"true"},
      "msisdn" : {"type":"keyword","index":"true"},
      "nsapi" : {"type":"integer","index":"true"},
      "rai" : {"type":"keyword","index":"true"},
      "rat-type" : {"type":"keyword","index":"true"},
      "selection" : {"type":"keyword","index":"true"},
      "seqnum" : {"type":"integer","index":"true"},
      "tunnel-idx" : {"type":"integer","index":"true"},
      "u-gsn" : {"type":"ip","index":"true"},
      "uli" : {"type":"keyword","index":"true"},
      "deny_cause" : {"type":"keyword","index":"true"},
      "dtlexp" : {"type":"keyword","index":"true"},
      "ietype" : {"type":"integer","index":"true"},
      "c-bytes" : {"type":"long","index":"true"},
      "c-ggsn" : {"type":"ip","index":"true"},
      "c-ggsn-teid" : {"type":"integer","index":"true"},
      "c-pkts" : {"type":"long","index":"true"},
      "c-sgsn" : {"type":"ip","index":"true"},
      "c-sgsn-teid" : {"type":"integer","index":"true"},
      "u-bytes" : {"type":"long","index":"true"},
      "u-ggsn" : {"type":"ip","index":"true"},
      "u-ggsn-teid" : {"type":"integer","index":"true"},
      "u-pkts" : {"type":"long","index":"true"},
      "u-sgsn" : {"type":"ip","index":"true"},
      "u-sgsn-teid" : {"type":"integer","index":"true"},
      "user_data" : {"type":"keyword","index":"true"},
      "cpaddr" : {"type":"ip","index":"true"},
      "cpteid" : {"type":"integer","index":"true"},
      "snetwork" : {"type":"keyword","index":"true"},
      "cpdladdr" : {"type":"ip","index":"true"},
      "cpdlisraddr" : {"type":"ip","index":"true"},
      "cpdlisrteid" : {"type":"integer","index":"true"},
      "cpdlteid" : {"type":"integer","index":"true"},
      "cpuladdr" : {"type":"ip","index":"true"},
      "cpulteid" : {"type":"integer","index":"true"},
      "attackcontext" : {"type":"keyword","index":"true"},
      "attackcontextid" : {"type":"keyword","index":"true"},
      "incidentserialno" : {"type":"integer","index":"true"},
      "collectedemail" : {"type":"keyword","index":"true"},
      "dstname" : {"type":"keyword","index":"true"},
      "dstssid" : {"type":"keyword","index":"true"},
      "dstuuid" : {"type":"keyword","index":"true"},
      "mastersrcmac" : {"type":"keyword","index":"true"},
      "osname" : {"type":"keyword","index":"true"},
      "osversion" : {"type":"keyword","index":"true"},
      "poluuid" : {"type":"keyword","index":"true"},
      "shaperdroprcvdbyte" : {"type":"integer","index":"true"},
      "shaperdropsentbyte" : {"type":"integer","index":"true"},
      "shaperperipdropbyte" : {"type":"integer","index":"true"},
      "shaperperipname" : {"type":"keyword","index":"true"},
      "shaperrcvdname" : {"type":"keyword","index":"true"},
      "shapersentname" : {"type":"keyword","index":"true"},
      "srcmac" : {"type":"keyword","index":"true"},
      "srcssid" : {"type":"keyword","index":"true"},
      "srcuuid" : {"type":"keyword","index":"true"},
      "trandisp" : {"type":"keyword","index":"true"},
      "tranip" : {"type":"ip","index":"true"},
      "tranport" : {"type":"integer","index":"true"},
      "transip" : {"type":"ip","index":"true"},
      "transport" : {"type":"integer","index":"true"},
      "unauthuser" : {"type":"keyword","index":"true"},
      "unauthusersource" : {"type":"keyword","index":"true"},
      "vpn" : {"type":"keyword","index":"true"},
      "vpntype" : {"type":"keyword","index":"true"},
      "vwpvlanid" : {"type":"integer","index":"true"},
      "rcvdpkt" : {"type":"integer","index":"true"},
      "sentpkt" : {"type":"integer","index":"true"},
      "centralnatid" : {"type":"integer","index":"true"},
      "countapp" : {"type":"integer","index":"true"},
      "countav" : {"type":"integer","index":"true"},
      "countdlp" : {"type":"integer","index":"true"},
      "countweb" : {"type":"integer","index":"true"},
      "dstcountry" : {"type":"keyword","index":"true"},
      "lanin" : {"type":"long","index":"true"},
      "lanout" : {"type":"long","index":"true"},
      "srccountry" : {"type":"keyword","index":"true"},
      "sslexempt" : {"type":"keyword","index":"true"},
      "utmaction" : {"type":"keyword","index":"true"},
      "wanin" : {"type":"integer","index":"true"},
      "wanoptapptype" : {"type":"keyword","index":"true"},
      "wanout" : {"type":"integer","index":"true"},
      "countemail" : {"type":"integer","index":"true"},
      "countips" : {"type":"integer","index":"true"},
      "policymode" : {"type":"keyword","index":"true"},
      "call_id" : {"type":"keyword","index":"true"},
      "dst_port" : {"type":"integer","index":"true"},
      "event_id" : {"type":"integer","index":"true"},
      "kind" : {"type":"keyword","index":"true"},
      "policy_id" : {"type":"integer","index":"true"},
      "src_port" : {"type":"integer","index":"true"},
      "voip_proto" : {"type":"keyword","index":"true"},
      "message_type" : {"type":"keyword","index":"true"},
      "request_name" : {"type":"keyword","index":"true"},
      "column" : {"type":"integer","index":"true"},
      "line" : {"type":"keyword","index":"true"},
      "malform_data" : {"type":"integer","index":"true"},
      "malform_desc" : {"type":"keyword","index":"true"},
      "phone" : {"type":"keyword","index":"true"},
      "constraint" : {"type":"keyword","index":"true"},
      "reqtype" : {"type":"keyword","index":"true"},
      "keyword" : {"type":"keyword","index":"true"},
      "urlfilteridx" : {"type":"integer","index":"true"},
      "urlfilterlist" : {"type":"keyword","index":"true"},
      "urltype" : {"type":"keyword","index":"true"},
      "catdesc" : {"type":"keyword","index":"true"},
      "quotaexceeded" : {"type":"keyword","index":"true"},
      "quotamax" : {"type":"long","index":"true"},
      "quotatype" : {"type":"keyword","index":"true"},
      "quotaused" : {"type":"long","index":"true"},
      "cat" : {"type":"integer","index":"true"},
      "ovrdid" : {"type":"integer","index":"true"},
      "ovrdtbl" : {"type":"keyword","index":"true"},
      "ruledata" : {"type":"keyword","index":"true"},
      "ruletype" : {"type":"keyword","index":"true"},
      "contenttype" : {"type":"keyword","index":"true"}
    }
  }
}
'

echo "====Template setting Paloalto===="
curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:$ES_PASS -XPUT "https://localhost:9200/_template/palo_template_01?pretty" -H 'Content-Type: application/json' -d '
{
  "index_patterns" : ["palo_syslog_*"],
  "settings" : {
    "number_of_shards" : 1,
    "number_of_replicas" : 0,
    "refresh_interval" : "1s",
    "index.lifecycle.name": "palo_ilm_policy_001",      
    "index.lifecycle.rollover_alias": "palo_syslog" 
  },
  "mappings" : {
      "dynamic_templates": [{
        "defaultmapping_notanalyzed": {
          "match": "*",
          "match_mapping_type": "string",
          "mapping": {"type": "keyword", "index": "false"}
        }
      }],
    "properties": {
      "hostname": {"type":"keyword","index":"true"},
      "receive_time": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "serial": {"type":"keyword","index":"true"},
      "type": {"type":"keyword","index":"true"},
      "subtype_traffic": {"type":"keyword","index":"true"},
      "time_generated": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "src": {"type":"ip","index":"true"},
      "dst": {"type":"ip","index":"true"},
      "natsrc": {"type":"ip","index":"true"},
      "natdst": {"type":"ip","index":"true"},
      "rule": {"type":"keyword","index":"true"},
      "srcuser": {"type":"keyword","index":"true"},
      "dstuser": {"type":"keyword","index":"true"},
      "app": {"type":"keyword","index":"true"},
      "vsys": {"type":"keyword","index":"true"},
      "from": {"type":"keyword","index":"true"},
      "to": {"type":"keyword","index":"true"},
      "inbound_if": {"type":"keyword","index":"true"},
      "outbound_if": {"type":"keyword","index":"true"},
      "logset": {"type":"keyword","index":"true"},
      "sessionid": {"type":"keyword","index":"true"},
      "repeatcnt": {"type":"integer","index":"true"},
      "sport": {"type":"keyword","index":"true"},
      "dport": {"type":"keyword","index":"true"},
      "natsport": {"type":"keyword","index":"true"},
      "natdport": {"type":"keyword","index":"true"},
      "flags": {"type":"keyword","index":"true"},
      "proto": {"type":"keyword","index":"true"},
      "action": {"type":"keyword","index":"true"},
      "bytes": {"type":"long","index":"true"},
      "bytes_sent": {"type":"long","index":"true"},
      "bytes_received": {"type":"long","index":"true"},
      "packets": {"type":"integer","index":"true"},
      "start": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "elapsed": {"type":"integer","index":"true"},
      "category": {"type":"keyword","index":"true"},
      "seqno": {"type":"keyword","index":"true"},
      "actionflags": {"type":"keyword","index":"true"},
      "srcloc": {"type":"keyword","index":"true"},
      "dstloc": {"type":"keyword","index":"true"},
      "pkts_sent": {"type":"integer","index":"true"},
      "pkts_received": {"type":"integer","index":"true"},
      "session_end_reason": {"type":"keyword","index":"true"},
      "cloud": {"type":"keyword","index":"true"},
      "contenttype": {"type":"keyword","index":"true"},
      "direction": {"type":"keyword","index":"true"},
      "filedigest": {"type":"keyword","index":"true"},
      "filetype": {"type":"keyword","index":"true"},
      "misc_file": {"type":"keyword","index":"true"},
      "misc_url": {"type":"keyword","index":"true"},
      "misc_virus": {"type":"keyword","index":"true"},
      "misc_wildfire": {"type":"keyword","index":"true"},
      "pcap_id": {"type":"keyword","index":"true"},
      "recipient": {"type":"keyword","index":"true"},
      "referer": {"type":"keyword","index":"true"},
      "reportid": {"type":"keyword","index":"true"},
      "sender": {"type":"keyword","index":"true"},
      "severity": {"type":"keyword","index":"true"},
      "subject": {"type":"keyword","index":"true"},
      "subtype_threat": {"type":"keyword","index":"true"},
      "threatid": {"type":"keyword","index":"true"},
      "user_agent": {"type":"keyword","index":"true"},
      "wildfire_result": {"type":"keyword","index":"true"},
      "xff": {"type":"keyword","index":"true"},
      "vsys_name": {"type":"keyword","index":"true"},
      "device_name": {"type":"keyword","index":"true"},
      "action_source": {"type":"keyword","index":"true"},
      "source_vm_uuid": {"type":"keyword","index":"true"},
      "destination_vm_uuid": {"type":"keyword","index":"true"},
      "http_method": {"type":"keyword","index":"true"},
      "tunnel_id_imsi": {"type":"keyword","index":"true"},
      "monitor_tag_imei": {"type":"keyword","index":"true"},
      "parent_session_id": {"type":"keyword","index":"true"},
      "parent_start_time": {"type":"keyword","index":"true"},
      "tunnel_type": {"type":"keyword","index":"true"},
      "threat_category": {"type":"keyword","index":"true"},
      "content_version": {"type":"keyword","index":"true"},
      "sctp_association_id": {"type":"keyword","index":"true"},
      "payload_protocol_id": {"type":"keyword","index":"true"},
      "http_headers": {"type":"keyword","index":"true"},
      "url_category": {"type":"keyword","index":"true"},
      "url_category_risk": {"type":"keyword","index":"true"},
      "sctp_chunks": {"type":"keyword","index":"true"},
      "sctp_chunks_sent": {"type":"keyword","index":"true"},
      "sctp_chunks_received": {"type":"keyword","index":"true"},
      "rule_uuid": {"type":"keyword","index":"true"},
      "http2_connection": {"type":"keyword","index":"true"},
      "link_change_count": {"type":"keyword","index":"true"},
      "policy_id": {"type":"keyword","index":"true"},
      "link_switches": {"type":"keyword","index":"true"},
      "sdwan_cluster": {"type":"keyword","index":"true"},
      "sdwan_device_type": {"type":"keyword","index":"true"},
      "sdwan_cluster_type": {"type":"keyword","index":"true"},
      "sdwan_site": {"type":"keyword","index":"true"},
      "dynamic_usergroup_name": {"type":"keyword","index":"true"},
      "xff_ip": {"type":"ip","index":"true"},
      "src_category": {"type":"keyword","index":"true"},
      "src_profile": {"type":"keyword","index":"true"},
      "src_model": {"type":"keyword","index":"true"},
      "src_vendor": {"type":"keyword","index":"true"},
      "src_osfamily": {"type":"keyword","index":"true"},
      "src_osversion": {"type":"keyword","index":"true"},
      "src_host": {"type":"keyword","index":"true"},
      "src_mac": {"type":"keyword","index":"true"},
      "dst_category": {"type":"keyword","index":"true"},
      "dst_profile": {"type":"keyword","index":"true"},
      "dst_model": {"type":"keyword","index":"true"},
      "dst_vendor": {"type":"keyword","index":"true"},
      "dst_osfamily": {"type":"keyword","index":"true"},
      "dst_osversion": {"type":"keyword","index":"true"},
      "dst_host": {"type":"keyword","index":"true"},
      "dst_mac": {"type":"keyword","index":"true"},
      "container_id": {"type":"keyword","index":"true"},
      "pod_namespace": {"type":"keyword","index":"true"},
      "pod_name": {"type":"keyword","index":"true"},
      "src_edl": {"type":"keyword","index":"true"},
      "dst_edl": {"type":"keyword","index":"true"},
      "hostid": {"type":"keyword","index":"true"},
      "serialnumber": {"type":"keyword","index":"true"},
      "src_dag": {"type":"keyword","index":"true"},
      "dst_dag": {"type":"keyword","index":"true"},
      "session_owner": {"type":"keyword","index":"true"},
      "high_res_timestamp": {"type":"date","format":"strict_date_optional_time"},
      "nssai_sst": {"type":"keyword","index":"true"},
      "nssai_sd": {"type":"keyword","index":"true"},
      "subcategory_of_app": {"type":"keyword","index":"true"},
      "category_of_app": {"type":"keyword","index":"true"},
      "technology_of_app": {"type":"keyword","index":"true"},
      "risk_of_app": {"type":"keyword","index":"true"},
      "characteristic_of_app": {"type":"keyword","index":"true"},
      "container_of_app": {"type":"keyword","index":"true"},
      "is_saas_of_app": {"type":"keyword","index":"true"},
      "sanctioned_state_of_app": {"type":"keyword","index":"true"},
      "domain_edl": {"type":"keyword","index":"true"},
      "partial_hash": {"type":"keyword","index":"true"},
      "reason": {"type":"keyword","index":"true"},
      "justification": {"type":"keyword","index":"true"},
      "eventid": {"type":"keyword","index":"true"},
      "stage": {"type":"keyword","index":"true"},
      "auth_method": {"type":"keyword","index":"true"},
      "srcregion": {"type":"keyword","index":"true"},
      "machinename": {"type":"keyword","index":"true"},
      "public_ip": {"type":"keyword","index":"true"},
      "public_ipv6": {"type":"keyword","index":"true"},
      "private_ip": {"type":"keyword","index":"true"},
      "private_ipv6": {"type":"keyword","index":"true"},
      "client_ver": {"type":"keyword","index":"true"},
      "client_os": {"type":"keyword","index":"true"},
      "client_os_ver": {"type":"keyword","index":"true"},
      "opaque": {"type":"keyword","index":"true"},
      "status": {"type":"keyword","index":"true"},
      "location": {"type":"keyword","index":"true"},
      "login_duration": {"type":"keyword","index":"true"},
      "connect_method": {"type":"keyword","index":"true"},
      "error_code": {"type":"keyword","index":"true"},
      "portal": {"type":"keyword","index":"true"},
      "selection_type": {"type":"keyword","index":"true"},
      "response_time": {"type":"keyword","index":"true"},
      "priority": {"type":"keyword","index":"true"},
      "gateway": {"type":"keyword","index":"true"},
      "vsys_id": {"type":"keyword","index":"true"},
      "offloaded": {"type":"keyword","index":"true"},
      "cloud_reportid": {"type":"keyword","index":"true"},
      "error": {"type":"keyword","index":"true"},
      "attempted_gateways": {"type":"keyword","index":"true"}
    }
  }
}
'

echo "====Template setting Nozomi===="
curl --cacert /etc/elasticsearch/certs/ca/ca.crt -u elastic:$ES_PASS -XPUT "https://localhost:9200/_template/nozomi_template_01?pretty" -H 'Content-Type: application/json' -d '
 {
   "index_patterns" : ["nozomi_syslog_*"],
   "settings" : {
     "number_of_shards" : 1,
     "number_of_replicas" : 0,
     "refresh_interval" : "1s",
     "index.lifecycle.name": "nozomi_ilm_policy_001",      
    "index.lifecycle.rollover_alias": "nozomi_syslog" 
   },
   "mappings" : {
     "dynamic_templates": [{
       "defaultmapping_notanalyzed": {
         "match": "*",
         "match_mapping_type": "string",
         "mapping": {"type": "keyword", "index": "false"}
       }
     }],
     "properties": {  
       "receive_time": {"type":"date","format":"strict_date_optional_time||epoch_second"},
       "time_generated": {"type":"date","format":"strict_date_optional_time||epoch_millis"},   
       "hostname": {"type":"keyword","index":"true"},
       "event": {"type":"keyword","index":"true"},
       "cef_version": {"type":"integer","index":"true"},
       "vender": {"type":"keyword","index":"true"},
       "product": {"type":"keyword","index":"true"},
       "osverson": {"type":"keyword","index":"true"},
       "type": {"type":"keyword","index":"true"},
       "subtype": {"type":"keyword","index":"true"},
       "title": {"type":"keyword","index":"true"},
       "severity": {"type":"integer","index":"true"},
       "app": {"type":"keyword","index":"true"},
       "dvc": {"type":"ip","index":"true"},
       "dvchost": {"type":"keyword","index":"true"},
       "risk": {"type":"float","index":"true"},
       "is_security": {"type":"keyword","index":"true"},
       "event_id": {"type":"keyword","index":"true"},
       "parents": {
         "type":"text",
         "index":"true",
         "fields": {
           "parent": {
             "type": "keyword",
             "index":"true",
             "ignore_above": 1024
           }
         }},
       "schema_version": {"type":"keyword","index":"true"},
       "dst": {"type":"ip","index":"true"},
       "dst_host": {"type":"keyword","index":"true"},
       "dst_mac": {"type":"keyword","index":"true"},
       "dport": {"type":"keyword","index":"true"},
       "msgs": {
         "type": "text",
         "index":"true",
         "fields": {
           "msg": {
             "type": "keyword",
             "index":"true",
             "ignore_above": 1024
           }
         }},
       "src": {"type":"ip","index":"true"},
       "src_mac": {"type":"keyword","index":"true"},
       "sport": {"type":"keyword","index":"true"},
       "proto": {"type":"keyword","index":"true"},
       "suser": {"type":"keyword","index":"true"},
       "browser": {"type":"keyword","index":"true"},
       "cs1Label": {"type":"keyword","index":"true"},
       "cs2Label": {"type":"keyword","index":"true"},
       "cs3Label": {"type":"keyword","index":"true"},
       "cs5Label": {"type":"keyword","index":"true"},
       "cs6Label": {"type":"keyword","index":"true"},
       "flexString1": {"type":"keyword","index":"true"},
       "flexString2": {"type":"keyword","index":"true"},
       "flexString3": {"type":"keyword","index":"true"},
       "flexString1Label": {"type":"keyword","index":"true"},
       "flexString2Label": {"type":"keyword","index":"true"},
       "flexString3Label": {"type":"keyword","index":"true"}
     }
   }
 }
 '

echo " "
echo "**********************"
echo "Setting completed."
echo "**********************"