#! /bin/bash

curl -X PUT "localhost:9200/_template/template_01?pretty" -H 'Content-Type: application/json' -d '
{
  "template" : "palo_syslog_*",
  "settings" : {
    "number_of_shards" : 1,
    "number_of_replicas" : 0,
    "refresh_interval" : "1s"
  },
  "mappings" : {
    "dynamic_templates": [{
      "defaultmapping_notanalyzed": {
        "match": "*",
        "match_mapping_type": "string",
        "mapping": {"type": "keyword", "index": "false"}
      }
    }],
    "properties": {
      "hostname": {"type":"keyword","index":"true"},
      "receive_time": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "serial": {"type":"keyword","index":"true"},
      "type": {"type":"keyword","index":"true"},
      "subtype_traffic": {"type":"keyword","index":"true"},
      "time_generated": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "src": {"type":"ip","index":"true"},
      "dst": {"type":"ip","index":"true"},
      "natsrc": {"type":"ip","index":"true"},
      "natdst": {"type":"ip","index":"true"},
      "rule": {"type":"keyword","index":"true"},
      "srcuser": {"type":"keyword","index":"true"},
      "dstuser": {"type":"keyword","index":"true"},
      "app": {"type":"keyword","index":"true"},
      "vsys": {"type":"keyword","index":"true"},
      "from": {"type":"keyword","index":"true"},
      "to": {"type":"keyword","index":"true"},
      "inbound_if": {"type":"keyword","index":"true"},
      "outbound_if": {"type":"keyword","index":"true"},
      "logset": {"type":"keyword","index":"true"},
      "sessionid": {"type":"keyword","index":"true"},
      "repeatcnt": {"type":"integer","index":"true"},
      "sport": {"type":"keyword","index":"true"},
      "dport": {"type":"keyword","index":"true"},
      "natsport": {"type":"keyword","index":"true"},
      "natdport": {"type":"keyword","index":"true"},
      "flags": {"type":"keyword","index":"true"},
      "proto": {"type":"keyword","index":"true"},
      "action": {"type":"keyword","index":"true"},
      "bytes": {"type":"long","index":"true"},
      "bytes_sent": {"type":"long","index":"true"},
      "bytes_received": {"type":"long","index":"true"},
      "packets": {"type":"integer","index":"true"},
      "start": {"type":"date","format":"strict_date_optional_time||epoch_second"},
      "elapsed": {"type":"integer","index":"true"},
      "category": {"type":"keyword","index":"true"},
      "seqno": {"type":"keyword","index":"true"},
      "actionflags": {"type":"keyword","index":"true"},
      "srcloc": {"type":"keyword","index":"true"},
      "dstloc": {"type":"keyword","index":"true"},
      "pkts_sent": {"type":"integer","index":"true"},
      "pkts_received": {"type":"integer","index":"true"},
      "session_end_reason": {"type":"keyword","index":"true"},
      "cloud": {"type":"keyword","index":"true"},
      "contenttype": {"type":"keyword","index":"true"},
      "direction": {"type":"keyword","index":"true"},
      "filedigest": {"type":"keyword","index":"true"},
      "filetype": {"type":"keyword","index":"true"},
      "misc_file": {"type":"keyword","index":"true"},
      "misc_url": {"type":"keyword","index":"true"},
      "misc_virus": {"type":"keyword","index":"true"},
      "misc_wildfire": {"type":"keyword","index":"true"},
      "pcap_id": {"type":"keyword","index":"true"},
      "recipient": {"type":"keyword","index":"true"},
      "referer": {"type":"keyword","index":"true"},
      "reportid": {"type":"keyword","index":"true"},
      "sender": {"type":"keyword","index":"true"},
      "severity": {"type":"keyword","index":"true"},
      "subject": {"type":"keyword","index":"true"},
      "subtype_threat": {"type":"keyword","index":"true"},
      "threatid": {"type":"keyword","index":"true"},
      "user_agent": {"type":"keyword","index":"true"},
      "wildfire_result": {"type":"keyword","index":"true"},
      "xff": {"type":"keyword","index":"true"},
      "vsys_name": {"type":"keyword","index":"true"},
      "device_name": {"type":"keyword","index":"true"},
      "action_source": {"type":"keyword","index":"true"},
      "source_vm_uuid": {"type":"keyword","index":"true"},
      "destination_vm_uuid": {"type":"keyword","index":"true"},
      "http_method": {"type":"keyword","index":"true"},
      "tunnel_id_imsi": {"type":"keyword","index":"true"},
      "monitor_tag_imei": {"type":"keyword","index":"true"},
      "parent_session_id": {"type":"keyword","index":"true"},
      "parent_start_time": {"type":"keyword","index":"true"},
      "tunnel_type": {"type":"keyword","index":"true"},
      "threat_category": {"type":"keyword","index":"true"},
      "content_version": {"type":"keyword","index":"true"},
      "sctp_association_id": {"type":"keyword","index":"true"},
      "payload_protocol_id": {"type":"keyword","index":"true"},
      "http_headers": {"type":"keyword","index":"true"},
      "url_category": {"type":"keyword","index":"true"},
      "url_category_risk": {"type":"keyword","index":"true"},
      "rule_uuid": {"type":"keyword","index":"true"},
      "http2_connection": {"type":"keyword","index":"true"},
      "dynamic_usergroup_name": {"type":"keyword","index":"true"}
    }
  }
}
'
